[package]
name = "advent_of_code_2020_day19_part1"
version = "0.2.0"
authors = ["Sean Owens <seangabrielowens@gmail.com>"]
edition = "2018"

[dependencies]
aoc_rust_common = { path =  "../../../aoc_rust_common"}
